name = "PackageName"
uuid = "18071168-1550-49a9-bd40-6ccc7e296a77"
authors = ["GL Dimaguila <ikeedee07@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
